CSP_train: true
aggregation: sum
batch_size: 1
ckpt_path: ./lightning_logs/version_5/checkpoints/last.ckpt
diffusion_schedule: cosine
diffusion_steps: 1000
diffusion_type: gaussian
do_test: true
do_train: false
do_valid_only: true
fp16: true
hidden_dim: 256
inference_diffusion_steps: 50
inference_schedule: cosine
inference_trick: ddim
input_nodes: ./nodes_191120.csv
learning_rate: 0.0002
logger_name: null
lr_scheduler: cosine-decay
n_layers: 12
num_epochs: 10
num_workers: 16
project_name: flavor_diffusion
resume_weight_only: false
storage_path: .
test_split: ./output_subgraphs/25/subgraphs_test.json
training_split: ./output_subgraphs/25/subgraphs_test.json
training_split_label_dir: null
use_activation_checkpoint: false
validation_split: ./output_subgraphs/25/subgraphs_test.json
weight_decay: 0.0001
